name: paster
description: A flutter project to store all your legal document numbers at your finger tips. Forget storing numbers in in-secure text files. We are at your rescue. Use our app to store all your important document numbers, debit/credit cards, etc and easily copy it when you need to paste it somewhere. All your numbers are stored in an ENCRYPTED and LOCAL database. We absolutely never ever store any of your data on our servers. You can chose to opt in for automatic backups which is stored on YOUR google drive account and no one else can access it.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  moor: ^3.2.0
  path_provider: ^1.6.11
  flutter_hooks: ^0.11.0
  async: any
  intl:
  path:
  uuid:
  sqlite3_flutter_libs: ^0.4.1
dependency_overrides:
  moor:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^4.1.0
  gen_lang: ^0.1.3

scripts:
  moor-watch: flutter pub run build_runner watch
  apk: flutter pub run build_runner build && flutter build apk --split-per-abi
  gen_lang: flutter pub run gen_lang:generate
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/images/cards/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
